version: '3.9'
services:
  db:
    image: postgres
    build: ./database/
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: test

  py-app:
    build: ./app/
    container_name: py-container
    ports:
      - "9001:9001"